-- Detailed quote intake schema for Supabase.
-- Safe to keep in version control and paste into the SQL editor if you are not
-- using `supabase db push` yet.

create extension if not exists pgcrypto;

create schema if not exists private;

do $$
begin
  create type public.quote_request_status as enum (
    'new',
    'contacted',
    'quoted',
    'scheduled',
    'won',
    'lost',
    'spam',
    'archived'
  );
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.quote_request_priority as enum ('standard', 'hot', 'vip');
exception
  when duplicate_object then null;
end $$;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.quote_requests (
  id uuid primary key default gen_random_uuid(),
  request_number bigint generated by default as identity unique,
  status public.quote_request_status not null default 'new',
  priority public.quote_request_priority not null default 'standard',

  full_name text not null,
  email text,
  phone text,
  preferred_contact_method text not null default 'call'
    check (preferred_contact_method in ('call', 'text', 'email')),

  move_type text not null default 'local-moving'
    check (
      move_type in (
        'local-moving',
        'long-distance',
        'packing',
        'storage',
        'commercial-moving',
        'residential-moving',
        'other'
      )
    ),
  service_bundle text[] not null default '{}',
  preferred_move_date date,
  move_date_flexibility text not null default 'flexible'
    check (move_date_flexibility in ('asap', 'flexible', 'date-locked', 'month-known')),

  origin_city text,
  origin_state text,
  origin_postal_code text,
  destination_city text,
  destination_state text,
  destination_postal_code text,

  origin_home_type text
    check (origin_home_type in ('house', 'apartment', 'condo', 'townhome', 'office', 'storage', 'other')),
  destination_home_type text
    check (destination_home_type in ('house', 'apartment', 'condo', 'townhome', 'office', 'storage', 'other')),
  bedroom_count smallint check (bedroom_count is null or bedroom_count between 0 and 20),
  estimated_square_feet integer check (estimated_square_feet is null or estimated_square_feet >= 0),
  inventory_size text
    check (inventory_size in ('studio', '1-bedroom', '2-bedroom', '3-bedroom', '4-bedroom+', 'office', 'mixed', 'other')),

  packing_scope text not null default 'none'
    check (packing_scope in ('none', 'partial', 'full', 'fragile-only')),
  storage_needed boolean not null default false,
  storage_timeline text,

  origin_has_stairs boolean not null default false,
  destination_has_stairs boolean not null default false,
  origin_stair_flights smallint check (origin_stair_flights is null or origin_stair_flights between 0 and 20),
  destination_stair_flights smallint check (destination_stair_flights is null or destination_stair_flights between 0 and 20),
  origin_has_elevator boolean not null default false,
  destination_has_elevator boolean not null default false,
  long_carry_origin boolean not null default false,
  long_carry_destination boolean not null default false,

  special_items text[] not null default '{}',
  inventory_summary text,
  access_notes text,
  message text,

  source text not null default 'website'
    check (source in ('website', 'phone', 'email', 'manual', 'referral', 'chat')),
  source_page text,
  referrer_url text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  gclid text,
  msclkid text,
  raw_submission jsonb not null default '{}'::jsonb,

  internal_notes text,
  assigned_to uuid references auth.users (id) on delete set null,
  follow_up_at timestamptz,
  contacted_at timestamptz,
  quoted_at timestamptz,
  quoted_price_low numeric(10, 2),
  quoted_price_high numeric(10, 2),
  quote_currency text not null default 'USD',
  scheduled_move_at timestamptz,
  won_at timestamptz,
  lost_at timestamptz,
  lost_reason text,

  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),

  constraint quote_requests_name_check
    check (char_length(btrim(full_name)) >= 2),
  constraint quote_requests_contact_check
    check (coalesce(nullif(btrim(phone), ''), nullif(btrim(email), '')) is not null),
  constraint quote_requests_quote_range_check
    check (
      quoted_price_low is null
      or quoted_price_high is null
      or quoted_price_low <= quoted_price_high
    )
);

comment on table public.quote_requests is
  'Detailed intake table for moving-company quote requests, including marketing attribution and sales follow-up fields.';

comment on column public.quote_requests.move_type is
  'Matches the current site form values: local-moving, long-distance, packing, storage, or other.';

comment on column public.quote_requests.raw_submission is
  'Optional full JSON payload from the frontend, useful when the form evolves faster than the schema.';

create index if not exists quote_requests_status_created_at_idx
  on public.quote_requests (status, created_at desc);

create index if not exists quote_requests_preferred_move_date_idx
  on public.quote_requests (preferred_move_date);

create index if not exists quote_requests_assigned_to_status_idx
  on public.quote_requests (assigned_to, status);

create index if not exists quote_requests_email_idx
  on public.quote_requests ((lower(email)));

create index if not exists quote_requests_phone_idx
  on public.quote_requests (phone);

create index if not exists quote_requests_source_created_at_idx
  on public.quote_requests (source, created_at desc);

create index if not exists quote_requests_raw_submission_gin_idx
  on public.quote_requests using gin (raw_submission);

drop trigger if exists set_quote_requests_updated_at on public.quote_requests;

create trigger set_quote_requests_updated_at
before update on public.quote_requests
for each row
execute function private.set_updated_at();

alter table public.quote_requests enable row level security;

drop policy if exists "Public can submit new quote requests" on public.quote_requests;

create policy "Public can submit new quote requests"
on public.quote_requests
for insert
to anon, authenticated
with check (
  status = 'new'
  and priority = 'standard'
  and source in ('website', 'chat')
  and assigned_to is null
  and internal_notes is null
  and follow_up_at is null
  and contacted_at is null
  and quoted_at is null
  and quoted_price_low is null
  and quoted_price_high is null
  and scheduled_move_at is null
  and won_at is null
  and lost_at is null
  and lost_reason is null
);

-- No public select/update/delete policies are created here.
-- Read and write access beyond inserts should happen via the service role, an
-- admin app, or additional staff-only policies that match your auth model.
